apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cli
  template:
    metadata:
      labels:
        app: api-cli
    spec:
      containers:
        - image: gcr.io/breachalert/breachalert-services-api-cli
          imagePullPolicy: Always
          name: api-cli
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/breachalert_production"
            - name: APP_DOMAIN
              value: "alexthings.co.uk"
            - name: APP_URL
              value: "https://alexthings.co.uk"
            - name: POSTMARK_FROM
              value: "no-reply@alexthings.co.uk"
            - name: POSTMARK_APIKEY
              value: "abc"
            - name: UPLOADS_STORE
              value: "gcs"
            - name: UPLOADS_GCS_BUCKET
              value: "breachalert-production-uploads"
          volumeMounts:
            - name: jobs-cache
              mountPath: /workdir/data
      volumes:
        - name: jobs-cache
          emptyDir: {}
